// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: administrator_async.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdministrationAsyncReq_ReqKind int32

const (
	AdministrationAsyncReq_CreateResource       AdministrationAsyncReq_ReqKind = 0
	AdministrationAsyncReq_DeleteResource       AdministrationAsyncReq_ReqKind = 1
	AdministrationAsyncReq_PutAttribute         AdministrationAsyncReq_ReqKind = 2
	AdministrationAsyncReq_DeleteAttribute      AdministrationAsyncReq_ReqKind = 3
	AdministrationAsyncReq_CreateInheritanceRel AdministrationAsyncReq_ReqKind = 4
	AdministrationAsyncReq_DeleteInheritanceRel AdministrationAsyncReq_ReqKind = 5
	AdministrationAsyncReq_CreatePolicy         AdministrationAsyncReq_ReqKind = 6
	AdministrationAsyncReq_DeletePolicy         AdministrationAsyncReq_ReqKind = 7
)

// Enum value maps for AdministrationAsyncReq_ReqKind.
var (
	AdministrationAsyncReq_ReqKind_name = map[int32]string{
		0: "CreateResource",
		1: "DeleteResource",
		2: "PutAttribute",
		3: "DeleteAttribute",
		4: "CreateInheritanceRel",
		5: "DeleteInheritanceRel",
		6: "CreatePolicy",
		7: "DeletePolicy",
	}
	AdministrationAsyncReq_ReqKind_value = map[string]int32{
		"CreateResource":       0,
		"DeleteResource":       1,
		"PutAttribute":         2,
		"DeleteAttribute":      3,
		"CreateInheritanceRel": 4,
		"DeleteInheritanceRel": 5,
		"CreatePolicy":         6,
		"DeletePolicy":         7,
	}
)

func (x AdministrationAsyncReq_ReqKind) Enum() *AdministrationAsyncReq_ReqKind {
	p := new(AdministrationAsyncReq_ReqKind)
	*p = x
	return p
}

func (x AdministrationAsyncReq_ReqKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdministrationAsyncReq_ReqKind) Descriptor() protoreflect.EnumDescriptor {
	return file_administrator_async_proto_enumTypes[0].Descriptor()
}

func (AdministrationAsyncReq_ReqKind) Type() protoreflect.EnumType {
	return &file_administrator_async_proto_enumTypes[0]
}

func (x AdministrationAsyncReq_ReqKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdministrationAsyncReq_ReqKind.Descriptor instead.
func (AdministrationAsyncReq_ReqKind) EnumDescriptor() ([]byte, []int) {
	return file_administrator_async_proto_rawDescGZIP(), []int{0, 0}
}

type AdministrationAsyncReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind          AdministrationAsyncReq_ReqKind `protobuf:"varint,1,opt,name=kind,proto3,enum=proto.AdministrationAsyncReq_ReqKind" json:"kind,omitempty"`
	ReqMarshalled []byte                         `protobuf:"bytes,2,opt,name=reqMarshalled,proto3" json:"reqMarshalled,omitempty"`
}

func (x *AdministrationAsyncReq) Reset() {
	*x = AdministrationAsyncReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_administrator_async_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdministrationAsyncReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdministrationAsyncReq) ProtoMessage() {}

func (x *AdministrationAsyncReq) ProtoReflect() protoreflect.Message {
	mi := &file_administrator_async_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdministrationAsyncReq.ProtoReflect.Descriptor instead.
func (*AdministrationAsyncReq) Descriptor() ([]byte, []int) {
	return file_administrator_async_proto_rawDescGZIP(), []int{0}
}

func (x *AdministrationAsyncReq) GetKind() AdministrationAsyncReq_ReqKind {
	if x != nil {
		return x.Kind
	}
	return AdministrationAsyncReq_CreateResource
}

func (x *AdministrationAsyncReq) GetReqMarshalled() []byte {
	if x != nil {
		return x.ReqMarshalled
	}
	return nil
}

type AdministrationAsyncResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *AdministrationAsyncResp) Reset() {
	*x = AdministrationAsyncResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_administrator_async_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdministrationAsyncResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdministrationAsyncResp) ProtoMessage() {}

func (x *AdministrationAsyncResp) ProtoReflect() protoreflect.Message {
	mi := &file_administrator_async_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdministrationAsyncResp.ProtoReflect.Descriptor instead.
func (*AdministrationAsyncResp) Descriptor() ([]byte, []int) {
	return file_administrator_async_proto_rawDescGZIP(), []int{1}
}

func (x *AdministrationAsyncResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_administrator_async_proto protoreflect.FileDescriptor

var file_administrator_async_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x5f,
	0x61, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xac, 0x02, 0x0a, 0x16, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x69, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x73, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x71, 0x12, 0x39, 0x0a,
	0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x25, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x41, 0x73, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x71, 0x2e, 0x52, 0x65, 0x71, 0x4b, 0x69,
	0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x72, 0x65, 0x71, 0x4d,
	0x61, 0x72, 0x73, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0d, 0x72, 0x65, 0x71, 0x4d, 0x61, 0x72, 0x73, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x22, 0xb0,
	0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x10, 0x00, 0x12, 0x12,
	0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x50, 0x75, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x10, 0x03, 0x12, 0x18, 0x0a, 0x14, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x49, 0x6e, 0x68, 0x65, 0x72, 0x69, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65,
	0x6c, 0x10, 0x04, 0x12, 0x18, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e, 0x68,
	0x65, 0x72, 0x69, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x6c, 0x10, 0x05, 0x12, 0x10, 0x0a,
	0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x10, 0x06, 0x12,
	0x10, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x10,
	0x07, 0x22, 0x2f, 0x0a, 0x17, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x41, 0x73, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x42, 0x1e, 0x5a, 0x1c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x63, 0x31, 0x32, 0x73, 0x2f, 0x6f, 0x6f, 0x72, 0x74, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61,
	0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_administrator_async_proto_rawDescOnce sync.Once
	file_administrator_async_proto_rawDescData = file_administrator_async_proto_rawDesc
)

func file_administrator_async_proto_rawDescGZIP() []byte {
	file_administrator_async_proto_rawDescOnce.Do(func() {
		file_administrator_async_proto_rawDescData = protoimpl.X.CompressGZIP(file_administrator_async_proto_rawDescData)
	})
	return file_administrator_async_proto_rawDescData
}

var file_administrator_async_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_administrator_async_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_administrator_async_proto_goTypes = []interface{}{
	(AdministrationAsyncReq_ReqKind)(0), // 0: proto.AdministrationAsyncReq.ReqKind
	(*AdministrationAsyncReq)(nil),      // 1: proto.AdministrationAsyncReq
	(*AdministrationAsyncResp)(nil),     // 2: proto.AdministrationAsyncResp
}
var file_administrator_async_proto_depIdxs = []int32{
	0, // 0: proto.AdministrationAsyncReq.kind:type_name -> proto.AdministrationAsyncReq.ReqKind
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_administrator_async_proto_init() }
func file_administrator_async_proto_init() {
	if File_administrator_async_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_administrator_async_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdministrationAsyncReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_administrator_async_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdministrationAsyncResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_administrator_async_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_administrator_async_proto_goTypes,
		DependencyIndexes: file_administrator_async_proto_depIdxs,
		EnumInfos:         file_administrator_async_proto_enumTypes,
		MessageInfos:      file_administrator_async_proto_msgTypes,
	}.Build()
	File_administrator_async_proto = out.File
	file_administrator_async_proto_rawDesc = nil
	file_administrator_async_proto_goTypes = nil
	file_administrator_async_proto_depIdxs = nil
}
