// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: evaluator.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthorizationReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subject        *Resource    `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Object         *Resource    `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	EnvAttributes  []*Attribute `protobuf:"bytes,3,rep,name=envAttributes,proto3" json:"envAttributes,omitempty"`
	PermissionName string       `protobuf:"bytes,4,opt,name=permissionName,proto3" json:"permissionName,omitempty"`
}

func (x *AuthorizationReq) Reset() {
	*x = AuthorizationReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_evaluator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorizationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationReq) ProtoMessage() {}

func (x *AuthorizationReq) ProtoReflect() protoreflect.Message {
	mi := &file_evaluator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationReq.ProtoReflect.Descriptor instead.
func (*AuthorizationReq) Descriptor() ([]byte, []int) {
	return file_evaluator_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizationReq) GetSubject() *Resource {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *AuthorizationReq) GetObject() *Resource {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *AuthorizationReq) GetEnvAttributes() []*Attribute {
	if x != nil {
		return x.EnvAttributes
	}
	return nil
}

func (x *AuthorizationReq) GetPermissionName() string {
	if x != nil {
		return x.PermissionName
	}
	return ""
}

type AuthorizationResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authorized bool `protobuf:"varint,1,opt,name=authorized,proto3" json:"authorized,omitempty"`
}

func (x *AuthorizationResp) Reset() {
	*x = AuthorizationResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_evaluator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorizationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationResp) ProtoMessage() {}

func (x *AuthorizationResp) ProtoReflect() protoreflect.Message {
	mi := &file_evaluator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationResp.ProtoReflect.Descriptor instead.
func (*AuthorizationResp) Descriptor() ([]byte, []int) {
	return file_evaluator_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorizationResp) GetAuthorized() bool {
	if x != nil {
		return x.Authorized
	}
	return false
}

type GetGrantedPermissionsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subject       *Resource    `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	EnvAttributes []*Attribute `protobuf:"bytes,2,rep,name=envAttributes,proto3" json:"envAttributes,omitempty"`
}

func (x *GetGrantedPermissionsReq) Reset() {
	*x = GetGrantedPermissionsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_evaluator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGrantedPermissionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGrantedPermissionsReq) ProtoMessage() {}

func (x *GetGrantedPermissionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_evaluator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGrantedPermissionsReq.ProtoReflect.Descriptor instead.
func (*GetGrantedPermissionsReq) Descriptor() ([]byte, []int) {
	return file_evaluator_proto_rawDescGZIP(), []int{2}
}

func (x *GetGrantedPermissionsReq) GetSubject() *Resource {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *GetGrantedPermissionsReq) GetEnvAttributes() []*Attribute {
	if x != nil {
		return x.EnvAttributes
	}
	return nil
}

type GetGrantedPermissionsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Permissions []*GrantedPermission `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
}

func (x *GetGrantedPermissionsResp) Reset() {
	*x = GetGrantedPermissionsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_evaluator_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGrantedPermissionsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGrantedPermissionsResp) ProtoMessage() {}

func (x *GetGrantedPermissionsResp) ProtoReflect() protoreflect.Message {
	mi := &file_evaluator_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGrantedPermissionsResp.ProtoReflect.Descriptor instead.
func (*GetGrantedPermissionsResp) Descriptor() ([]byte, []int) {
	return file_evaluator_proto_rawDescGZIP(), []int{3}
}

func (x *GetGrantedPermissionsResp) GetPermissions() []*GrantedPermission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

var File_evaluator_proto protoreflect.FileDescriptor

var file_evaluator_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x65, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc6, 0x01, 0x0a, 0x10, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x29, 0x0a, 0x07, 0x73, 0x75,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x07, 0x73, 0x75,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x27, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x36,
	0x0a, 0x0d, 0x65, 0x6e, 0x76, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x52, 0x0d, 0x65, 0x6e, 0x76, 0x41, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x33,
	0x0a, 0x11, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69,
	0x7a, 0x65, 0x64, 0x22, 0x7d, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x65,
	0x64, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x12,
	0x29, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x36, 0x0a, 0x0d, 0x65, 0x6e,
	0x76, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x52, 0x0d, 0x65, 0x6e, 0x76, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x73, 0x22, 0x57, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x64,
	0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x3a, 0x0a, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x72, 0x61,
	0x6e, 0x74, 0x65, 0x64, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0b,
	0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x32, 0xaf, 0x01, 0x0a, 0x0d,
	0x4f, 0x6f, 0x72, 0x74, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x40, 0x0a,
	0x09, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12,
	0x5c, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x50, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x50, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x50, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x1e, 0x5a,
	0x1c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x31, 0x32, 0x73,
	0x2f, 0x6f, 0x6f, 0x72, 0x74, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_evaluator_proto_rawDescOnce sync.Once
	file_evaluator_proto_rawDescData = file_evaluator_proto_rawDesc
)

func file_evaluator_proto_rawDescGZIP() []byte {
	file_evaluator_proto_rawDescOnce.Do(func() {
		file_evaluator_proto_rawDescData = protoimpl.X.CompressGZIP(file_evaluator_proto_rawDescData)
	})
	return file_evaluator_proto_rawDescData
}

var file_evaluator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_evaluator_proto_goTypes = []interface{}{
	(*AuthorizationReq)(nil),          // 0: proto.AuthorizationReq
	(*AuthorizationResp)(nil),         // 1: proto.AuthorizationResp
	(*GetGrantedPermissionsReq)(nil),  // 2: proto.GetGrantedPermissionsReq
	(*GetGrantedPermissionsResp)(nil), // 3: proto.GetGrantedPermissionsResp
	(*Resource)(nil),                  // 4: proto.Resource
	(*Attribute)(nil),                 // 5: proto.Attribute
	(*GrantedPermission)(nil),         // 6: proto.GrantedPermission
}
var file_evaluator_proto_depIdxs = []int32{
	4, // 0: proto.AuthorizationReq.subject:type_name -> proto.Resource
	4, // 1: proto.AuthorizationReq.object:type_name -> proto.Resource
	5, // 2: proto.AuthorizationReq.envAttributes:type_name -> proto.Attribute
	4, // 3: proto.GetGrantedPermissionsReq.subject:type_name -> proto.Resource
	5, // 4: proto.GetGrantedPermissionsReq.envAttributes:type_name -> proto.Attribute
	6, // 5: proto.GetGrantedPermissionsResp.permissions:type_name -> proto.GrantedPermission
	0, // 6: proto.OortEvaluator.Authorize:input_type -> proto.AuthorizationReq
	2, // 7: proto.OortEvaluator.GetGrantedPermissions:input_type -> proto.GetGrantedPermissionsReq
	1, // 8: proto.OortEvaluator.Authorize:output_type -> proto.AuthorizationResp
	3, // 9: proto.OortEvaluator.GetGrantedPermissions:output_type -> proto.GetGrantedPermissionsResp
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_evaluator_proto_init() }
func file_evaluator_proto_init() {
	if File_evaluator_proto != nil {
		return
	}
	file_model_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_evaluator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorizationReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_evaluator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorizationResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_evaluator_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGrantedPermissionsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_evaluator_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGrantedPermissionsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_evaluator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_evaluator_proto_goTypes,
		DependencyIndexes: file_evaluator_proto_depIdxs,
		MessageInfos:      file_evaluator_proto_msgTypes,
	}.Build()
	File_evaluator_proto = out.File
	file_evaluator_proto_rawDesc = nil
	file_evaluator_proto_goTypes = nil
	file_evaluator_proto_depIdxs = nil
}
